[package]
name = "auto"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
enigo = "0.6.1"
# windows = { version = "0.61.3", features = [
#     "Win32_Graphics",
#     "Win32_Graphics_Gdi",
# ] }
